### ISSUE TITLE
[CU-862hz23aa] UI / Label Rendering Issue?

### ISSUE THREAD

**Issue by rroline** [VirtusLab-Open-Source/strapi-plugin-comments#180] opened 2022-12-24 09:05 UTC
Hello! 

I followed the installation instructions and after running `yarn build` the plugin appeared, but seems to have issue with rendering the values associated with the various plugin fields. Did I miss a critical configuration step? The plugin does not appear to be functional either. 

I am running a custom docker image of strapi v4.5.3 and node 14.21.2. All packages/modules were installed using yarn. Any help would be greatly appreciated. Thanks! 

![image](https://user-images.githubusercontent.com/59673517/209428760-ad60dffb-e2d6-4daa-b1f4-cc723825610f.png)

**Comment by Antontsyk** [comment] 2022-12-26 21:00
Hello! 
I have same issue also.
`  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.1.2",
    "@strapi/plugin-i18n": "4.5.4",
    "@strapi/plugin-users-permissions": "4.5.4",
    "@strapi/strapi": "4.5.4",
    "better-sqlite3": "7.6.2",
    "pg": "^8.8.0",
    "pg-connection-string": "^2.5.0",
    "sharp": "^0.31.2",
    "strapi-middleware-cache": "^2.1.8",
    "strapi-middleware-upload-plugin-cache": "^2.1.0",
    "strapi-plugin-comments": "^2.2.3",
    "strapi-plugin-custom-api": "^1.0.3",
    "strapi-plugin-fuzzy-search": "^1.10.2",
    "strapi-plugin-import-export-entries": "^1.18.0",
    "strapi-plugin-local-image-sharp": "^1.2.1",
    "strapi-plugin-rest-cache": "^4.2.5",
    "strapi-plugin-sitemap": "^2.0.8",
    "strapi-plugin-transformer": "^2.1.1",
    "strapi-provider-rest-cache-memory": "^4.2.5"
  },`

<img width="1568" alt="Снимок экрана 2022-12-27 в 00 57 34" src="https://user-images.githubusercontent.com/20355799/209583094-f830ae6f-d58a-491e-ab83-7b34ede32102.png">

**Comment by cyp3rius** [comment] 2022-12-27 15:12
@Antontsyk @rroline may I ask you both to verify if you've got the translation file properly placed within the plugin package in `node_modules`? Also the console logs would be appreciated as by doing same steps I cannot reproduce that bug.

**Comment by Antontsyk** [comment] 2022-12-27 16:56
@cyp3rius 
![Uploading Снимок экрана 2022-12-27 в 20.53.10.png…]()

**Comment by Antontsyk** [comment] 2022-12-27 16:57
<img width="1737" alt="Снимок экрана 2022-12-27 в 20 53 10" src="https://user-images.githubusercontent.com/20355799/209697816-8fbb7076-fa60-4e11-83cb-d700e4feaff7.png">
@cyp3rius

**Comment by rroline** [comment] 2022-12-27 17:03
I am running this in docker so the files are automatically installed from the repo when i run yarn build. The translation files are present in the plugin folder after installation.

![image](https://user-images.githubusercontent.com/59673517/209697986-e6375fd7-6c00-48ff-95ba-eec9b8b6b9d0.png)

**Comment by rroline** [comment] 2022-12-27 17:25
@cyp3rius - Which logs are you looking for? The build logs when installing the plugin package? The build logs from starting the strapi image? Or the console logs when that module/plugin is accessed? 

I looked in all three places and didnt see anything that jumped out at me, but I am happy to send whatever you think would help. Thanks!

**Comment by Jahorse** [comment] 2022-12-27 22:02
I'm having the same issue with similar dependencies. I also see `en.json`, `fr.json`, and `pt-BR.json` in the `translations` folder and I don't have any related messages in the JS debugger console when I visit `http://localhost:1337/admin/settings/comments`.

How is the language supposed to get set for the plugin? I haven't seen any documentation about how to set which translation file to use.

**Comment by Bodokh** [comment] 2022-12-29 06:50
I am using node 16 with strapi 4.4.3 with the latest comments package also running into the same issue

**Comment by cyp3rius** [comment] 2022-12-29 08:33
Thank you all for the details. Digging into that and hope today to provide a hotfix once I'll reproduce the behavior.

**Comment by cyp3rius** [comment] 2022-12-29 10:00
Fix is ready, should be reviewed and released today. Mostly it started to happen with some combination of plugins installed (maybe number, not sure), the `async` execution been scheduled and didn't executed in time of bootstrap.

**Comment by cyp3rius** [comment] 2022-12-29 12:00
Fixed in `2.2.4`

**Closed by cyp3rius** 2022-12-29 12:00 UTC
Labels: bug, investigation, v4, moderation panel

**Comment by LeoMoshko** [comment] 2023-03-28 14:23
@cyp3rius Hi Mateusz, Unfortunately it broke for the case when there is a different language than there are translations. My issues was that by adding a custom locale while the plugin is active, the loadTrads method was throwing an error.
This was in my case due to the fact that the plugin only supports the following languages: en, fr, tr and "pt-BR".
