### ISSUE TITLE
why is authorAvatar null?

### ISSUE THREAD

**Issue by Nisthar** [VirtusLab-Open-Source/strapi-plugin-comments#122] opened 2022-03-20 05:13 UTC
I have avatar set on the user. I am using users-permission plugin. Also custom population like

`?populate[0]=authorUser.avatar` doesn't work

![image](https://user-images.githubusercontent.com/11994157/159149182-39540464-62ca-4cba-bb34-d4ade075d983.png)

**Comment by Nisthar** [comment] 2022-03-20 07:50
I guess you have to specify it when creating. I was trying to update with authorAvatar.

**Comment by cyp3rius** [comment] 2022-03-20 09:02
Hello @Nisthar, the populate feature is on our product board so there won't be any customizations needed.

**Comment by Nisthar** [comment] 2022-03-30 07:50
@cyp3rius The problem with that is the `users-permission` plugin doesn't populate `avatar` field by default, so its always undefined. And there's no way to pass custom populate to the comments.

**Comment by cyp3rius** [comment] 2022-03-30 08:13
@Nisthar  as I said earlier we've got the population support planned.

**Comment by cyp3rius** [comment] 2022-03-30 08:51
Duplicate of #113

**Closed by cyp3rius** 2022-03-30 08:51 UTC
Labels: duplicate
