### ISSUE TITLE
Is there any plan to add ability to reply inside panel?

### ISSUE THREAD

**Issue by hosnas** [VirtusLab-Open-Source/strapi-plugin-comments#156] opened 2022-08-17 10:47 UTC
like wordpress, we need to reply to the comment inside our panel. right now there is no way to do it properly.

**Comment by cyp3rius** [comment] 2022-08-17 10:48
Hello @hosnas, this functionality is in progress already. Keep you posted.

**Comment by cyp3rius** [comment] 2022-08-22 06:34
Duplicate of #55

**Closed by cyp3rius** 2022-08-22 06:34 UTC
Labels: duplicate, enhancement, v4, moderation panel
