### ISSUE TITLE
Comments are created, and can be fetched, but they are not loaded in Strapi

### ISSUE THREAD

**Issue by M1ck0** [VirtusLab-Open-Source/strapi-plugin-comments#117] opened 2022-02-27 15:06 UTC
When I create comments through graphql it works as it should (with some queries missing, read below for this). But I get this error when trying to load comments in Strapi. This is the image

![image](https://user-images.githubusercontent.com/19279947/155887683-e09f0f18-4f38-4689-84f1-0adf909895c6.png)

Any ideas what could be the issue? This is log in the console

```[2022-02-27 16:01:58.342] error: Cannot read properties of null (reading 'split')
TypeError: Cannot read properties of null (reading 'split')
    at getRelatedGroups (/home/m1ck0/Desktop/projects/portfolio-admin/node_modules/strapi-plugin-comments/server/services/utils/functions.js:52:42)
    at /home/m1ck0/Desktop/projects/portfolio-admin/node_modules/strapi-plugin-comments/server/services/common.js:198:55
    at Array.reduce (<anonymous>)
    at Object.findRelatedEntitiesFor (/home/m1ck0/Desktop/projects/portfolio-admin/node_modules/strapi-plugin-comments/server/services/common.js:197:31)
    at Object.findAll (/home/m1ck0/Desktop/projects/portfolio-admin/node_modules/strapi-plugin-comments/server/services/admin.js:137:63)
    at async returnBodyMiddleware (/home/m1ck0/Desktop/projects/portfolio-admin/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/home/m1ck0/Desktop/projects/portfolio-admin/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async serve (/home/m1ck0/Desktop/projects/portfolio-admin/node_modules/koa-static/index.js:59:5)
    at async returnBodyMiddleware (/home/m1ck0/Desktop/projects/portfolio-admin/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/home/m1ck0/Desktop/projects/portfolio-admin/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /home/m1ck0/Desktop/projects/portfolio-admin/node_modules/@strapi/strapi/lib/middlewares/body.js:25:7
    at async /home/m1ck0/Desktop/projects/portfolio-admin/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
    at async /home/m1ck0/Desktop/projects/portfolio-admin/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
    at async cors (/home/m1ck0/Desktop/projects/portfolio-admin/node_modules/@koa/cors/index.js:56:32)
    at async /home/m1ck0/Desktop/projects/portfolio-admin/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
    at async session (/home/m1ck0/Desktop/projects/portfolio-admin/node_modules/koa-session/index.js:41:7)
```

Also, these are all available queries and mutations for comments. Judging by the docs, some of them are missing, and are named incorrectly.

![image](https://user-images.githubusercontent.com/19279947/155887775-4d2bbe62-2a9f-4629-9664-17ddaa403184.png)

This is new Strapi installation.

I have custom `config/env/production/database.js` file with this content

```js
const parse = require('pg-connection-string').parse;
const config = parse(process.env.DATABASE_URL);
module.exports = ({ env }) => ({
  connection: {
    client: 'postgres',
    connection: {
      host: config.host,
      port: config.port,
      database: config.database,
      user: config.user,
      password: config.password,
      ssl: {
        rejectUnauthorized: false
      },
    },
    debug: false,
  },
});

```

Node: 16.13.1
Strapi: 4.1.1
npm: 8.1.2
yarn: 1.22.17
OS: Linux

**Comment by M1ck0** [comment] 2022-02-27 15:39
@cyp3rius Any ideas?

**Comment by cyp3rius** [comment] 2022-02-27 17:53
@M1ck0 as I see you have got disabled the plugin queries. And probably you've added comments to not existing collections. Can you please check what settings you got per this plugin? Settings -> Comments plugin -> configuration

Adding this via not supported queries (that I see on your screen) caused errors as you are loosing valodations.

**Comment by M1ck0** [comment] 2022-02-27 21:47
Settings are fine. They are added to collection Blogs, which is the only collection I currently have

![image](https://user-images.githubusercontent.com/19279947/155901209-37f43010-875c-4663-a680-64712b1c9e6c.png)
![image](https://user-images.githubusercontent.com/19279947/155901227-fd3af532-b21c-4791-93fc-be27e8054bcd.png)

And what do you mean by `disabled the plugin queries`? Could you point me to some docs about it, because I can't seem to find anything about it.

**Comment by M1ck0** [comment] 2022-02-27 21:49
As you can see here my `Public` group has following permissions

![image](https://user-images.githubusercontent.com/19279947/155901330-88a17319-e830-4ea2-b726-4fe303b47126.png)

**Comment by cyp3rius** [comment] 2022-02-28 08:16
Hello @M1ck0 I've schema on Strapi 4.1.1 and looks correct. Check please if you got it right. I assume you've added the comments via default Strapi mutation (which should be disabled) and that causes issues.

1. Have you restarted Strapi after changing settings?
2. Provide me please mutation query which you triggered

**Comment by M1ck0** [comment] 2022-02-28 09:09
I have restarted Strapi after changes. Currently, I reinstalled the whole strapi, still the same issue. These are the only mutations I have

![image](https://user-images.githubusercontent.com/19279947/155955426-86c874f6-1599-4510-9792-45a7f81b5dfe.png)

**Comment by cyp3rius** [comment] 2022-02-28 09:17
Can you please share your `config/plugins.js` ? I'm interested in about the ordering of plugins as based on our doc it might be important.

**Comment by M1ck0** [comment] 2022-02-28 09:21
I don't have `plugins.js`. Only files present in `config` directory are

```
admin.js
api.js
database.js
middleware.js
server.js
```

**Comment by M1ck0** [comment] 2022-02-28 09:34
Still the same. I did `yarn build` and `yarn develop` after adding `config/plugins.js` file with the content you provided.

**Comment by M1ck0** [comment] 2022-03-01 07:42
Any updates on this?

**Comment by cyp3rius** [comment] 2022-03-01 07:52
I'm trying different configurations to reproduce this. Also in a meantime checking the other way to enable GQL support of plugin. It's clearly visible that bootstrap didn't enable it as expected

**Comment by M1ck0** [comment] 2022-03-01 08:51
Can I do anything to help you with reproduction? This is really strange issue

**Comment by cyp3rius** [comment] 2022-03-01 15:27
Finally reproduced it, looking for a solution. Expect it in 1-2 days hopefully

**Comment by M1ck0** [comment] 2022-03-01 19:14
Okay great. If I can do anything to help, just tell me. Hopefully we will resolve it

**Comment by cyp3rius** [comment] 2022-03-02 10:16
@M1ck0 found the fix for this issue. Try to put such configuration:

```js
module.exports = {
  'comments': { enabled: true },
  'graphql': { enabled: true },
};
```

The problem is indeed what we have described in docs about [GraphQL](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments#additional-gql-configuration) configuration. Installed plugins are ordered by default somehow by Strapi and the custom Comment plugin schemas are not injected before GraphQL plugin runs. 

We will work on it with Strapi to figure out a way to "order" it properly. But as for now it should solve your issue and also it wont break anything existing :)

**Comment by M1ck0** [comment] 2022-03-02 10:21
@cyp3rius It is still not working. Everything is the same. I'll try to reinstall the whole project again later to see if it is working from scratch, then I'll come back to you with the result.

**Comment by cyp3rius** [comment] 2022-03-02 10:23
I've did it against the plain strapi example we've got prepared for this plugin + made a settings for at least single collection there.

**Comment by M1ck0** [comment] 2022-03-06 15:32
@cyp3rius I am sorry for not responding for a few days but I wasn't online. Here is something I discovered when installing new project and adding a plugin

![image](https://user-images.githubusercontent.com/19279947/156929995-ada4f129-611b-4350-b8c2-ceb3cc95a5b2.png)

Could this be helpful?

**Comment by M1ck0** [comment] 2022-03-06 15:41
@cyp3rius Could this be of any help?

![image](https://user-images.githubusercontent.com/19279947/156930099-3190b993-6bd3-4ceb-9060-99831ba50af2.png)

It is working now, but I thought I should provide you with this image if it was something important.
Thank you for your help. Initializing new project and using 
```
module.exports = {
  'comments': { enabled: true },
  'graphql': { enabled: true },
};
```
in `config/plugins.js` did the trick

**Comment by cyp3rius** [comment] 2022-03-06 16:26
Thats the dependency inside the GraphQL plugin so typical warning :)

I've already asked question to Strapi team to check if there is a possibility to force plugins orders by their dependencies as Thats purely the issue. By this trick with `plugins.js` you are forcing the ordering.

As its solved, lets close the issue and I will keep eye this.

**Closed** 2022-03-06 16:26 UTC
Labels: solved, v4, graphql

**Comment by M1ck0** [comment] 2022-03-19 00:02
@cyp3rius same thing happens with strapi 4.1.5.

**Comment by cyp3rius** [comment] 2022-03-30 07:10
Strapi didn't fixed it I assume :) So the trick must be applied as for now.

**Comment by gbdubs** [comment] 2023-07-09 13:09
Just putting this here for folks who can't find their missing query types (i.e. `findAllInHierarchy` not in the schema/not queryable) with this setup. I had to explicitly add the collection types to `Settings > Comments > General Configuration > Enable comments only for` in order for the generated GQL code for the query types to be in the resulting schema + queryable through GQL.
